name: E2E Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Install dependencies
        run: mise run ci:install

      - name: Run check
        env:
          PUBLIC_PH_TOKEN: 'fake-token'
          PH_API_KEY: 'fake-key'
          PH_PROJECT_ID: '12345'
        run: mise run check

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Install dependencies
        run: mise run ci:install

      - name: Run E2E tests
        run: mise run test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
